version: v1.0.0.{build}
os: Visual Studio 2015

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://gist.githubusercontent.com/PureKrome/0f79e25693d574807939/raw/8cf3160c9516ef1f4effc825c0a44acc918a0b5a/appveyor-build-info.ps'))
  
install:
# Use the install script to grab the latest dotnet install
- ps: iex .\dotnet-latest.ps1

# Prepend newly installed dotnet cli to the PATH of this build (this cannot be
# done from inside the powershell script as it would require to restart
# the parent CMD process).
- "SET PATH=C:\\Program Files\\dotnet\\bin;%PATH%"

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '1.0.0.{build}'
  assembly_file_version: '1.0.0.{build}'

before_build:
- cmd: >-
    dotnet restore src\Client
build_script:
- cmd: >-
    dotnet pack src\Client --configuration Release --output "artifacts\bin\Client"
test: off